dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-deploy-dockerhub-example .
      - docker images
      - docker tag travis-ci-deploy-dockerhub-example $DOCKER_USERNAME/travis-ci-deploy-dockerhub-example
      - docker push $DOCKER_USERNAME/travis-ci-deploy-dockerhub-example
    - stage: test
      script: docker run --rm $DOCKER_USERNAME/travis-ci-deploy-dockerhub-example cat hello.txt
    - script: docker run --rm $DOCKER_USERNAME/travis-ci-deploy-dockerhub-example cat hello.txt